### ISSUE TITLE
很棒的团队，怎么加入你们？

### ISSUE THREAD

**Issue by andyidea** [doraemon-home/doraemon-home.github.io#69]

**Comment by LeungGeorge** [comment]
很高兴你能加入我们！
邀请你了：
You've invited andy.li to doraemon-home! They'll be receiving an email shortly. They can also visit https://github.com/doraemon-home to accept the invitation.

加入后，可以参考 readme 参与到项目中来：
https://github.com/doraemon-home/doraemon-home.github.io/blob/master/README.md

**Comment by andyidea** [comment]
已经加入，在接下来的时间里，希望可以帮助到团队，共同成长！
